## File for testing some basic algorithms

In [1]:
import numpy as np
import scipy as scp

from scipy import fft

In [2]:
x = [x for x in range(16)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [3]:
max_ind = len(x)

evens = [0 for x in range(8)]
odds = [0 for x in range(8)]

for y in range(0, max_ind, 2):
    print(y)
    evens[y // 2] = x[y]
    odds[y // 2] = x[y + 1]

print(evens)
print(odds)

0
2
4
6
8
10
12
14
[0, 2, 4, 6, 8, 10, 12, 14]
[1, 3, 5, 7, 9, 11, 13, 15]


In [4]:
# exmaple sine vector
time = [x for x in range(32)]

sined = np.sin(time) * 1000

(np.real(sined) ** 2) + (np.imag(sined) ** 2)


array([0.00000000e+00, 7.08073418e+05, 8.26821810e+05, 1.99148567e+04,
       5.72750017e+05, 9.19535765e+05, 7.80730206e+04, 4.31631391e+05,
       9.78829740e+05, 1.69841646e+05, 2.95958969e+05, 9.99980413e+05,
       2.87910496e+05, 1.76540339e+05, 9.81302933e+05, 4.22874275e+05,
       8.28883197e+04, 9.24285137e+05, 5.63981845e+05, 2.24631780e+04,
       8.33469031e+05, 6.99992657e+05, 7.83456762e+01, 7.16088972e+05,
       8.20072170e+05, 1.75169858e+04, 5.81495390e+05, 9.14654916e+05,
       7.33899461e+04, 4.40409932e+05, 9.76206490e+05, 1.63246419e+05])

In [5]:
mult = 1000
twiddle = ((5 / 1000) + (7j / 1000))

even = (10 + 15j)
odd = (20 + 25j)

In [6]:
p = even * mult
q = odd * twiddle * mult


sum = p + q
diff = p - q
print(sum)
print(diff)

(9925+15265j)
(10075+14735j)


In [7]:

p = 10 + 15j
q = 20 + 25j

mult = 1000
twiddle = 5 + 7j
even_input_r = np.real(p) * mult
even_input_i = np.imag(p) * mult

odd_input_r = np.real(q)
odd_input_i = np.imag(q)

q_odd_real = (odd_input_r * np.real(twiddle)) - (odd_input_i * np.imag(twiddle))
q_odd_imag = (odd_input_r * np.imag(twiddle)) + (odd_input_i * np.real(twiddle))

sumy = complex(even_input_r + q_odd_real, even_input_i + q_odd_imag)
diffy = complex(even_input_r - q_odd_real, even_input_i - q_odd_imag)

print(sumy)
print(diffy)

(9925+15265j)
(10075+14735j)


In [13]:
# exmaple sine vector
time = [x * 0.1 for x in range(8)]

sined = (1000 * np.sin(5 * time)).astype(int)

fft_t = list(fft.fft(sined))

#fft_m = [1000 * ((np.real(x) ** 2) + (np.imag(x) ** 2)) for x in fft_t]

for x in fft_t:
    print(x)

(13340-0j)
0j
(7.923070424951838e-15+9.60115897731838e-14j)
(6.048023836129324e-14+4.621017316167779e-14j)
0j
(-2054.6015510839147+4407.404217424966j)
0j
(2.796231242682619e-14+2.4666795180078545e-14j)
(6.01981465919691e-14-1.0324790309899765e-14j)
0j
(-1865+1805j)
0j
(-7.77637290383322e-14+4.373651360616653e-14j)
(-1.0396729980463098e-14+7.872809909614484e-14j)
0j
(-1835.3984489160853+747.4042174249657j)
0j
(-4.291465591493015e-14-7.851130754388505e-15j)
(-2.548865287131493e-14+4.19502858571175e-14j)
0j
(-1830-0j)
-0j
(-2.548865287131493e-14-4.19502858571175e-14j)
(-4.291465591493015e-14+7.851130754388505e-15j)
-0j
(-1835.3984489160853-747.4042174249657j)
-0j
(-1.0396729980463098e-14-7.872809909614484e-14j)
(-7.77637290383322e-14-4.373651360616653e-14j)
-0j
(-1865-1805j)
-0j
(6.01981465919691e-14+1.0324790309899765e-14j)
(2.796231242682619e-14-2.4666795180078545e-14j)
-0j
(-2054.6015510839147-4407.404217424966j)
-0j
(6.048023836129324e-14-4.621017316167779e-14j)
(7.923070424951838e-15

In [9]:
sined

array([   0.        ,  841.47098481,  909.29742683,  141.12000806,
       -756.80249531, -958.92427466, -279.4154982 ,  656.98659872,
        989.35824662,  412.11848524, -544.02111089, -999.99020655,
       -536.572918  ,  420.16703683,  990.60735569,  650.28784016,
       -287.90331667, -961.39749188, -750.98724677,  149.87720966,
        912.94525073,  836.65563854,   -8.85130929, -846.22040418,
       -905.57836201, -132.3517501 ,  762.55845048,  956.3759284 ,
        270.90578831, -663.63388421, -988.03162409, -404.03764532])

In [10]:
def get_even_index_values(buffer: list[float]) -> list[float]:
    return buffer[::2]

def get_odd_index_values(buffer: list[float]) -> list[float]:
    return buffer[1::2]

def fft_iteration(buffer: list[float], length: int, stride: int) -> list[float]: # stride start as 1
    if(length == 1):
        return buffer * 1000
    else:
        even_values = get_even_index_values(buffer)
        odd_values = get_odd_index_values(buffer)

        even_fft = fft_iteration(even_values, length // 2, stride * 2)
        odd_fft = fft_iteration(odd_values, length // 2, stride * 2)
    
    reassembled = [0 for x in range(length)]

    for index in range(length // 2):
        p = even_fft[index]
        #print((np.e ** (-2j * np.pi * index / length)))
        cd = odd_fft[index] * np.e ** (-2j * np.pi * index / length)
        q = complex(int(np.real(cd)), int(np.imag(cd)))

        reassembled[index] = p + q
        reassembled[index + (length // 2)] = p - q

    return reassembled

In [11]:
# butterfly test

length = 32
even_fft = [complex(i + 4, i + 1) for i in range(length // 2)]
print(even_fft)
odd_fft = [complex(i + 2, i + 5) for i in range(length // 2)]
print(odd_fft)
# even_fft = [10 + 15j]
# odd_fft = [20 + 25j]

reassembled = [0 for x in range(length)]

for index in range(length // 2):
    p = even_fft[index] * 1000
    q = odd_fft[index] * ((np.e ** (-2j * np.pi * index / length)) * 1000)

    reassembled[index] = p + q
    reassembled[index + (length // 2)] = p - q


print(reassembled)

[(4+1j), (5+2j), (6+3j), (7+4j), (8+5j), (9+6j), (10+7j), (11+8j), (12+9j), (13+10j), (14+11j), (15+12j), (16+13j), (17+14j), (18+15j), (19+16j)]
[(2+5j), (3+6j), (4+7j), (5+8j), (6+9j), (7+10j), (8+11j), (9+12j), (10+13j), (11+14j), (12+15j), (13+16j), (14+17j), (15+18j), (16+19j), (17+20j)]
[(6000+6000j), (9112.89777330646+7299.440716370998j), (12374.302156600776+7936.422998118647j), (15601.909925669544+7873.905733322351j), (18606.601717798214+7121.320343559643j), (21203.687754162667+5735.415044078206j), (23224.142316544872+3818.4814959256946j), (24525.23626298392+1514.016340564467j), (25000-1000j), (24585.000383467817-3519.9025926613303j), (23265.991799288226-5826.805875611786j), (21081.1007675859-7698.228688246723j), (18121.320343559644-8920.310216782971j), (14528.220009814659-9300.00651673985j), (10488.91269475612-8676.646035555885j), (6228.4566734676555-6932.2410823387945j), (2000-4000j), (887.1022266935397-3299.4407163709984j), (-374.30215660077556-1936.4229981186472j), (-1601.9

In [12]:
time = np.asarray([x for x in range(8)])

sined = (1000 * np.sin(time / 4)).astype(int)

# sined = [10 + 15j, 20 + 25j]
print(sined)

bins = fft_iteration(sined, len(sined), 1)

for i, b in enumerate(bins):
    print(f"Input: {sined[i]} Out: {np.real(b)} + {np.imag(b)}j")

[  0 247 479 681 841 948 997 983]
Input: 0 Out: 5176000.0 + 0.0j
Input: 247 Out: -1123135.0 + 1227228.0j
Input: 479 Out: -635000.0 + 469000.0j
Input: 681 Out: -558865.0 + 191228.0j
Input: 841 Out: -542000.0 + 0.0j
Input: 948 Out: -558865.0 + -191228.0j
Input: 997 Out: -635000.0 + -469000.0j
Input: 983 Out: -1123135.0 + -1227228.0j
